spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/springtest?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ENC(WEXv1Jhiqr1j11wDDt9WoQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:generator/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    cn.yq.demo: debug
server:
  ssl:
    key-store: src/main/resources/zimug-ssl-key.p12
    key-store-password: 123456
    key-store-type: PKCS12

jasypt:
  encryptor:
    password: root